### ISSUE TITLE
字频平衡

### ISSUE THREAD

**Issue by blackarrow3542** [Sanster/text_renderer#1]
感谢分享数据生成的代码！
请问有什么思路做字频平衡吗？有可以参考的程序吗

**Comment by Sanster** [comment]
@blackarrow3542 Hi，之前没有在做字符平衡这块，现在初步写了一个 [balancer.py](https://github.com/Sanster/text_renderer/blob/master/tools/balancer.py)，但是效果不好，而且很慢，你有找到什么可以参考的代码不？

**Comment by blackarrow3542** [comment]
Hi,
我用的比较笨的办法。。。
我是使用的中文维基，搜狗新闻和一些古诗词的语料库。
主要思路是用两个dict来统计原始语料库的字频来产生新的语料库。
我用的1级加2级汉字大概6000多字
dict1： key是字， value是frequency，
dict2： key是字， value是set， set里面保存含有这个字的句子，
然后每次从语料库读取一句话（尽量不要太长的话，可以按标点分一下）或者分词就看一下，这句话每个字的frequency，
然后frequency限制一下（比如50，就是这个字如果已经对应超过50个短语或者句子就不希望再对这个字增加语料了），如果一句话里面的所有字的frequency都太高就舍去这句话。
只要这句话有一个字的frequency不高就留待下一步。
检查这句话的每个字，是否已经在那个字的set里面，不在的话就更新，把这个字的frequency+1并把这句话加到对应字的set里面。
这样来生成一批新的语料，虽然去除了一些重复比最初的语料平衡一些，但是字频还是差很多，然后统计一下这个新语料的字频，直接把少的字补足数量，然后shuffle一下。随机生成的语料保存到另一个文件。

然后再调用你的程序生产几种不同长度的定长 ，或者https://github.com/hehongyu1995/chinese-ocr-train 的程序直接生成随机长度的文本图片。

然后用https://github.com/hehongyu1995/chinese-ocr-train  再根据我的场景生成一些特别的数据，比如： 日期、 数字id、 英文 id、 税率、金额、大写金额等等，再多生成一些经常出现的厂家地址信息名称  
大概一共搞了一千多万张图片

train的时候generator用PIL的thumbnail把所有图片都生成同样大小的。比如32*400  （主要我的真实数据有些有十几二十个字。。。要不然其实我觉得10个字的话32*256就够了）
训练时先用比较自然的（不平衡）语料的数据训练模型几个epoch，然后再在加入了随机语料的数据上训练
训练时用生成的数据training，用人工标记的真实数据validating来reduce lr和early stop。。。

**Comment by Sanster** [comment]
哇，好详细 👍，借鉴你的思路试试。

多结果的话，是不是可以结合 Language Model 来做？感觉想单纯从图像上再提高精度比较有限，结合语意应该是 OCR 很重要的一步。

用 chinese-ocr-train 生成的数据可以贴出来看看不，感觉你说的那种效果应该挺常见的，我看看怎么把它加到 text_renderer 里

**Comment by blackarrow3542** [comment]
![e0ed6a1d-9349-11e8-aa26-309c237f371c](https://user-images.githubusercontent.com/6055793/43368270-54a88b7a-9320-11e8-8f3a-7b3de6f1ba36.jpg)
![e0ed6a4a-9349-11e8-aa26-309c237f371c](https://user-images.githubusercontent.com/6055793/43368271-5d462d14-9320-11e8-9c1a-37e2de2d9e99.jpg)
![e0ed6a4d-9349-11e8-aa26-309c237f371c](https://user-images.githubusercontent.com/6055793/43368276-635124ca-9320-11e8-8295-5e3dc621ac7e.jpg)
![e0ed69b9-9349-11e8-aa26-309c237f371c](https://user-images.githubusercontent.com/6055793/43368284-7d8b3c5e-9320-11e8-8c3c-6289edd54941.jpg)
![e12137c2-9349-11e8-aa26-309c237f371c](https://user-images.githubusercontent.com/6055793/43368296-9ae90588-9320-11e8-8468-e8092f63d453.jpg)
![e12138bb-9349-11e8-aa26-309c237f371c](https://user-images.githubusercontent.com/6055793/43368303-aab09828-9320-11e8-9acb-07568959c2f1.jpg)
![e50278d7-9349-11e8-aa26-309c237f371c](https://user-images.githubusercontent.com/6055793/43368313-c90876ec-9320-11e8-867d-9e9b527a38f5.jpg)
![e121381b-9349-11e8-aa26-309c237f371c](https://user-images.githubusercontent.com/6055793/43368318-d5534f30-9320-11e8-84b1-bb4ea80c4c0a.jpg)

**Comment by XingBin111** [comment]
@blackarrow3542 你好, 请问: 
1. 为什么要使用语料来生成数据, 对比random的优势是什么, random模式似乎不需要考虑字频平衡的问题.
2. 

> 检查这句话的每个字，是否已经在那个字的set里面，不在的话就更新，把这个字的frequency+1并把这句话加到对应字的set里面。
> 这样来生成一批新的语料，虽然去除了一些重复比最初的语料平衡一些，但是字频还是差很多，然后统计一下这个新语料的字频，直接把少的字补足数量，然后shuffle一下。随机生成的语料保存到另一个文件。

少的字如何添加到新的预料库呢?会影响语料的语义信息吗?
