### ISSUE TITLE
为什么部分会生成这么小的字?

### ISSUE THREAD

**Issue by Ysnower** [Sanster/text_renderer#100]
![00000094](https://user-images.githubusercontent.com/44294242/93428034-5f6ce400-f8f1-11ea-8081-af0f9f1af631.jpg)

**Comment by Sanster** [comment]
- 如果你的「小」是指左边为什么有这么多 padding，那是因为这个项目是生成固定宽度的图片，左边宽度不太好控制，如果你不想要这个宽度，可以用新的项目：https://github.com/oh-my-ocr/text_renderer
- 如果你的「小」是指字较小，那是因为投影变换，你可以把投影变换的 max 设小
