### ISSUE TITLE
如果我不想让文字倾斜

### ISSUE THREAD

**Issue by yuanyuan1993** [Sanster/text_renderer#104]
这个，如果我不想让生成的文字倾斜 ，该怎么设置呢  谢谢

**Comment by initial-heart** [comment]
> 这个，如果我不想让生成的文字倾斜 ，该怎么设置呢 谢谢

我也想知道如何不让文字倾斜，请问你找到方法了吗

**Comment by Sanster** [comment]
使用新版，配置不要配投影变换 https://github.com/oh-my-ocr/text_renderer/blob/19fd3acaa258793d0767c8078f51d01d6caa9442/example_data/example.py#L30

**Comment by initial-heart** [comment]
> 使用新版，配置不要配投影变换 https://github.com/oh-my-ocr/text_renderer/blob/19fd3acaa258793d0767c8078f51d01d6caa9442/example_data/example.py#L30

好嘞，感谢
