### ISSUE TITLE
关于字体顺序问题

### ISSUE THREAD

**Issue by Hold-on-li** [Sanster/text_renderer#113]
请问一下，我给定的是这种循序的字符
![image](https://user-images.githubusercontent.com/87969070/153690051-b4951250-faaa-4f3d-9fb2-779333024c77.png)
但是输出的时候是随机的字符，关于这个随机的问题可以关闭吗？
![image](https://user-images.githubusercontent.com/87969070/153690106-7cbb7ba9-b6e8-4063-8b5f-0fed323f214b.png)

**Comment by Sanster** [comment]
可以用新项目里的 EnumCorpus  https://github.com/oh-my-ocr/text_renderer/blob/79895d20d21c12f0b81e1e5162ee0465e10bed72/example_data/example.py#L80

**Comment by Hold-on-li** [comment]
> 可以用新项目里的 EnumCorpus https://github.com/oh-my-ocr/text_renderer/blob/79895d20d21c12f0b81e1e5162ee0465e10bed72/example_data/example.py#L80

你好，新版本换成自己的数据集的时候不是很明白，配置文件在哪里？

**Comment by Sanster** [comment]
配置的方式和老版不一样，请先把 README 完整看一遍

**Comment by Hold-on-li** [comment]
> 配置的方式和老版不一样，请先把 README 完整看一遍

![image](https://user-images.githubusercontent.com/87969070/153694402-a5ecf8f6-b72c-4a27-88f0-aec8fd637702.png)
请问一下，这种格式的文件，如何改成自己的呢？我用txt打开更改之后，运行报错

**Comment by Sanster** [comment]
编码不对，你可以自己准备一个 txt，每行是你想要生成的字符串，然后用 EnumCorpus

**Comment by Hold-on-li** [comment]
> 编码不对，你可以自己准备一个 txt，每行是你想要生成的字符串，然后用 EnumCorpus

好的，谢谢您，还请问一下，字体加粗在哪边可以操作呢？
