### ISSUE TITLE
你好，可以加好友吗？  微信： lp9628

### ISSUE THREAD

**Issue by MachineLP** [Sanster/text_renderer#14]

**Comment by Sanster** [comment]
hi，有遇到什么 bug 嘛，直接开个 issue 讨论吧 😄

**Comment by zouj168** [comment]
应该不算bug，我把我遇到的情况和你描述一下，供你参考。

1. 语料文件只有一个，内容只有 0123456789X
2. 字体库文件用的是 OCRB10N.TTF，这个字体后来验证是英文字体。

      按照你readme说明，加了 --strict，生成还是方框，后来我在代码中做了修改，就是我在issue 说明的那块，问题就消除了。
准确来说，应该不算你代码中的bug，因为运行结果算是符合预期，但你代码中函数的字体文件编码格式参数用的是默认，这就造成了一些本来应该支持的字体结果没有支持。

     总体来说，你的项目效果还是很棒的，在此再次表示感谢！





tanhuong_1234@163.com
 
发件人： Qing
发送时间： 2018-10-09 17:31
收件人： Sanster/text_renderer
抄送： Subscribed
主题： Re: [Sanster/text_renderer] 。 (#14)
hi，有遇到什么 bug 嘛，直接开个 issue 讨论吧 ????
