### ISSUE TITLE
标签文件中的文字改成汉字的索引

### ISSUE THREAD

**Issue by evanfly** [Sanster/text_renderer#17]
默认生成的tmp_labels.txt标签的内容是  ‘   00000001 命形式原始得令人吃惊  ’ ，这种形式的，现在想把它改成  ‘ 44955828_2248996261.jpg 29 403 2 172 586 167 10 172 110 121 ’ 这种形式的，后面的10个整数对应其在 char_std_5990.txt （5990个汉字字符，网上下载的）中的索引，如果数据量较大的话，重新写个脚本进行转换应该比较耗时，能否直接修改作者的代码进行转换，如果可以，请指教，谢谢！

**Comment by ericosmic** [comment]
@evanfly   请问找到修改方法了吗？  我也想问这个问题

**Comment by evanfly** [comment]
> @evanfly 请问找到修改方法了吗？ 我也想问这个问题

generate_img()函数中改的，你可以参考下

im, word , unsupport_chars_flag = gen_img_retry(renderer, img_index)
    base_name = hashlib.sha1(im).hexdigest()
    # base_name = '{:08d}'.format(img_index)
    if not flags.viz:

        none_flag = 0
        # 字符转索引--std_5990.txt
        line1 = list(word)
        image_name = base_name + '.jpg'
        label_str = line1
        line_len = len(label_str)
        str_list = 'output3_chn/default/' + image_name + ' '
        for j in range(line_len):
            chn_char = chn_dict.get(label_str[j])
            str_list += str(chn_char) + ' '
            if(chn_char == None):
                none_flag += 1
        label = ''
        label = str_list

**Comment by ericosmic** [comment]
@evanfly     chn_dict是你自己写的模块吗？  unsupport_chars_flag  后面有什么用，这个变量也是在renderer.gen_img中增加的返回量？

**Comment by evanfly** [comment]
@ericosmic ,unsupport_chars_flag是指该字体不支持的字符，我改的是不支持的就不生成样本图像
def load_dictory(dic_name):
    info_str = []
    # dic_name = 'cn_5990.txt'
    with open(dic_name, 'r', encoding="utf8", errors='ignore') as d:
        info_list = [part.strip().replace('\t', '') for part in d.readlines()]
        info_str = ''.join(info_list)

    list1 = []

    ii = 0
    for i in range(len(info_list)):
        list1.append(i)
        ii += 1

    chn_dic = dict(zip(info_list, list1))
    return chn_dic

**Comment by wangziyannb** [comment]
可能有后来人看不太明白上边大佬之间的互动，这里我来给个小白版指南，其中会以注释形式插入我的理解。最后附带char_std_5990.txt，注意和chn.txt内的顺序不一样。最后获得的可用的label为tmp_labels.txt

于main.py中修改generate_img函数。自np.random.seed()一行开始。

im, word = gen_img_retry(renderer, img_index)
    base_name = hashlib.sha1(im).hexdigest()
 
    info_str = []
    dic_name = 'char_std_5990.txt'
    with open(dic_name, 'r', encoding="utf8", errors='ignore') as d:
     info_list = [part.strip().replace('\t', '') for part in d.readlines()]
    info_str = ''.join(info_list)
    list1 = []
    ii = 0
    for i in range(len(info_list)):
        list1.append(i)
        ii += 1
    chn_dict = dict(zip(info_list, list1))
    
    if not flags.viz:
        none_flag=0
        # 字符转索引--char_std_5990.txt
        line1 = list(word)
        image_name = base_name + '.jpg'
        label_str = line1
        line_len = len(label_str)
        str_list = image_name + ' '
        #上一行按照注释写法会在labels.txt内的“文件名.jpg“前加存储目录
        #str_list = flags.save_dir +”/“+ image_name + ' '
        for j in range(line_len):
            #调查会发现和文档错一位（行），取决于你初始位是0还是1
            chn_char = chn_dict.get(label_str[j])
            str_list += str(chn_char) + ' '
            if(chn_char == None):
                none_flag += 1
        label = ''
        label = str_list        
        fname = os.path.join(flags.save_dir, image_name)
        cv2.imwrite(fname, im)     

如还有其他疑问可以继续问我

[char_std_5990.txt](https://github.com/Sanster/text_renderer/files/4401659/char_std_5990.txt)
