### ISSUE TITLE
参数位置反了？

### ISSUE THREAD

**Issue by ares89** [Sanster/text_renderer#3]
https://github.com/Sanster/text_renderer/blob/5bb961b83df7c3c0b301cf3d35eef29951a90f9d/textrenderer/renderer.py#L127

是否应该
`` x_offset, y_offset = self.random_xy_offset( s_bbox_height, s_bbox_width,self.out_height, self.out_width) ``

**Comment by Sanster** [comment]
fixed in https://github.com/Sanster/text_renderer/commit/0ea8247e0d6d98762f99075363163a9700dbac04
