### ISSUE TITLE
如何生成彩色图片

### ISSUE THREAD

**Issue by aagainbeyond2** [Sanster/text_renderer#31]

**Comment by zhangchurong** [comment]
我也想问

**Comment by zhangchurong** [comment]
1、把./libs/utils.py 下的
bg = cv2.imdecode(np.fromfile(image_path, dtype=np.uint8), cv2.IMREAD_GRAYSCALE)
改成
bg = cv2.imdecode(np.fromfile(image_path, dtype=np.uint8),cv2.IMREAD_COLOR)
2、准备自己的背景图，注意如果混有原来的bg.png生成的图片会是彩色灰度混杂，放入data/bg文件夹下
这样应该就可以了

**Comment by zhangchurong** [comment]
> 1、把./libs/utils.py 下的
> bg = cv2.imdecode(np.fromfile(image_path, dtype=np.uint8), cv2.IMREAD_GRAYSCALE)
> 改成
> bg = cv2.imdecode(np.fromfile(image_path, dtype=np.uint8),cv2.IMREAD_COLOR)
> 2、准备自己的背景图，注意如果混有原来的bg.png生成的图片会是彩色灰度混杂，放入data/bg文件夹下
> 这样应该就可以了

发现还不够鸭
还得把一些加噪声的函数，从row,col =image.size改成 row,col,n = image.size

**Comment by soraalbert** [comment]
如果想要背景是彩色的话，需要更改bg目录下的图片

1.将renderer.py中gen_bg_from_image中的
scale = max(width / bg.shape[1], height / bg.shape[0])
out = cv2.resize(bg, None, fx=scale, fy=scale)
注释掉
并加入out=bg

2.修改libs/utils.py中 line87
cv2.IMREAD_COLOR

3.修改configs/default.yaml中line39 fraction=1
如果不修改的话会有50%的概率不从bg中的图片生成背景（而是随机生成背景）

 4.以及上述@zhangchurong 所说的操作即可

这是我试验后得到还算成功的例子
仅供参考~

**Comment by tongtong9293** [comment]
row,col =image.size 请问这句在哪呀，没找到呢？（只看见了  row, col = img.shape这句）
关于加噪声的是只改image.size 这一句就行吗？ @soraalbert @zhangchurong  望指点

**Comment by soraalbert** [comment]
> row,col =image.size 请问这句在哪呀，没找到呢？（只看见了 row, col = img.shape这句）
> 关于加噪声的是只改image.size 这一句就行吗？ @soraalbert @zhangchurong 望指点

row,col=image.size和row,col=img.shape差不多
其实你直接运行的时候就会看到这里报错的，因为你现在的背景图已经不再是单通道了，是三通道的。
你可以把noiser.py中同样的都修改了，试运行100个sample试试。应该是没有问题的。

**Comment by tfdetang** [comment]
我也有这个需求，后来自己改了下，可以生成彩色的文字与彩色背景了，已经提交了pr, 也可以直接去https://github.com/tfdetang/text_renderer
