### ISSUE TITLE
请问怎么生成字体大小不一的图片

### ISSUE THREAD

**Issue by jewelcai** [Sanster/text_renderer#43]
请问怎么生成字体大小不一的图片  比如如图所示
<img width="250" alt="屏幕快照 2019-03-25 上午11 47 36" src="https://user-images.githubusercontent.com/8166517/54894295-e86daf80-4ef4-11e9-89a6-afdc0caf867c.png">

**Comment by Sanster** [comment]
目前不支持

**Comment by jewelcai** [comment]
有没有什么思路可以分享？ 是不是得在canvas上画两次呢 ？

**Comment by HusterRC** [comment]
@jewelcai 画2张不同字体的图像，然后拼接起来就行了

**Comment by jewelcai** [comment]
已经搞定了
