### ISSUE TITLE
语料库

### ISSUE THREAD

**Issue by peterWon** [Sanster/text_renderer#6]
感谢您提供的便利！
请问您语料库的组织有什么要求吗，怎样才能兼顾中英文及阿拉伯数字的识别，有没有参考链接呢？
谢谢！

**Comment by peterWon** [comment]
多谢多谢！

**Comment by Sanster** [comment]
@zzhaohao 你是用的哪个 corpus_mode？是不是 length 指定地比较短，如果是 chn 模式的话 txt 文件的字数太少了，可以用随机模式

**Comment by zzhaohao** [comment]
@Sanster 谢谢！我刚才尝试了使用list模式，已经可以生成特定文字组合的样本了。

**Comment by LJXLJXLJX** [comment]
> 语料只要以 txt(utf8) 的格式放在 `--corpus_dir` 目录下就可以了，会递归地去加载。注意使用不同的语料时 `--corpus_mode` 要对应，比如中文语料要对应 `--corpus_mode=chn`
> 
> 要兼顾中英文和数字，可以分三次生成数据（`--output_dir`指向同一个目录）。以生成 500w 数据为例，可以 420w 从中文语料里生成，60w 万从英文语料，20w 随机数字生成，因为中文的字符集最大，所以占的比例肯定要最高，但具体怎么样比例最优我也不确定...
> 
> 几个语料库的参考链接：
> 
> * 中文语料库： http://www.sogou.com/labs/resource/cs.php
> * wiki 中英文语料库：https://dumps.wikimedia.org/enwiki/20180720/

这两个太大了,请问大佬有没有规模小一点的语料库。

**Comment by nissansz** [comment]
> 语料只要以 txt(utf8) 的格式放在 `--corpus_dir` 目录下就可以了，会递归地去加载。注意使用不同的语料时 `--corpus_mode` 要对应，比如中文语料要对应 `--corpus_mode=chn`
> 
> 要兼顾中英文和数字，可以分三次生成数据（`--output_dir`指向同一个目录）。以生成 500w 数据为例，可以 420w 从中文语料里生成，60w 万从英文语料，20w 随机数字生成，因为中文的字符集最大，所以占的比例肯定要最高，但具体怎么样比例最优我也不确定...
> 
> 几个语料库的参考链接：
> 
> * 中文语料库： http://www.sogou.com/labs/resource/cs.php
> * wiki 中英文语料库：https://dumps.wikimedia.org/enwiki/20180720/

有没有纯英文语料库。
现在训练crnn时发现，中文字符准确率可以，反而英文好像不太理想，怎么解决？
