### ISSUE TITLE
作者你好，我想请问一下，从语料库中生成需要的训练集时，如何保证我的数据集是平衡的。举个栗子说，我如何确保每个字符的出现的频率大致是相同的，如果数据不均匀，对最终的模型会有多大的影响？

### ISSUE THREAD

**Issue by yugengde** [Sanster/text_renderer#63]
语料只要以 txt(utf8) 的格式放在 `--corpus_dir` 目录下就可以了，会递归地去加载。注意使用不同的语料时 `--corpus_mode` 要对应，比如中文语料要对应 `--corpus_mode=chn`

要兼顾中英文和数字，可以分三次生成数据（`--output_dir`指向同一个目录）。以生成 500w 数据为例，可以 420w 从中文语料里生成，60w 万从英文语料，20w 随机数字生成，因为中文的字符集最大，所以占的比例肯定要最高，但具体怎么样比例最优我也不确定...

几个语料库的参考链接：
- 中文语料库： http://www.sogou.com/labs/resource/cs.php
- wiki 中英文语料库：https://dumps.wikimedia.org/enwiki/20180720/

_Originally posted by @Sanster in https://github.com/Sanster/text_renderer/issues/6#issuecomment-408352902_

**Comment by Sanster** [comment]
自定义一个corpus类，实现get_simple函数，在里面做字符平衡

**Comment by yugengde** [comment]
好的，我试试，谢谢啦
