### ISSUE TITLE
虚拟机ubuntu16生成样本卡住不动

### ISSUE THREAD

**Issue by hbulaoma** [Sanster/text_renderer#8]
我在虚拟机ubuntu16.04下，想测试下。直接运行python3 main.py会卡住不动，图像也没有生成。

laoma@ubuntu:~/text_renderer-master$ python3 main.py
Load fonts from /home/laoma/text_renderer-master/data/fonts/chn
Total fonts num: 1
Background num: 1
Loading corpus from: ./data/corpus
Loading chn corpus: 1/1
Generate text images in ./output/default
这里就卡住不动了，是环境没配置好吗？

**Comment by Sanster** [comment]
虚拟机有几个核？默认进程数是核数，至少要两个进程，试试手动指定进程数  `--num_processes=2`

**Comment by hbulaoma** [comment]
谢谢，可以了。就是这原因。我把虚拟机的核心数量增加了，就正常了。
