### ISSUE TITLE
关于语料随机选取问题

### ISSUE THREAD

**Issue by zcswdt** [Sanster/text_renderer#89]
您好，我读了您写的代码，写的非常的棒，但是我发现，您的代码对语料的选取是随机截断的，存在着某一段文字被重复选取的概率，和语料中某些内容没法选取的概率，请问我想生成的图片将语料中每个字都用到的话，这个怎么修改呢？谢谢了

**Comment by Ysnower** [comment]
老铁,我也在想这个问题   您解决了吗
@zcswdt

**Comment by Sanster** [comment]
新建一个 corpus，语料从头往后取，维护一个索引
