### ISSUE TITLE
python main.py

### ISSUE THREAD

**Issue by caoyangcr7** [Sanster/text_renderer#9]
你好，打扰了。我在直接运行python main.py 会报错：glob.glob(fonts_dir + '／**/*',recursive=True),提示多了recursive参数。删去recursive参数能运行，但是会在加载font和txt文件的时候报错.删去　" /** "后能正确加载文件（以上代码所在行数分别是 text_renderer/libs/font_utils.py/line18和 text_renderer/textrenderer/corpus.py/line20），再次运行python main.py时一直反馈异常，输出　Retry gen_image（异常所在main.py中line71,应该是render.py的gen_image()函数执行出错）我是在ubuntu14和ubuntu18里面跑的，难道只能在ubuntu16里跑么？
　　谢谢了。

**Comment by caoyangcr7** [comment]
删去 " /** ",前面显示漏了。。

**Comment by Sanster** [comment]
python 什么版本的？只测试过 3.5，3.6

**Comment by caoyangcr7** [comment]
Python3.4....🤣🤣🤣🤣

**Comment by Sanster** [comment]
glob 递归的 feature 3.5 以后才有的…

**Comment by caoyangcr7** [comment]
好吧，还是要给个star.〈😐ノ
