### ISSUE TITLE
关于语料库选择问题

### ISSUE THREAD

**Issue by Ianwtg** [Sanster/text_renderer#94]
首先感谢博主开源的这么优秀的数据集工具，代码结构非常清楚，调参自由度很高。

我想要生成包含英文字母、数字和符号的数据集，博主能否告知一些语料库，或者烦劳告知我一下如何科学的构建语料库？我这边自己生成的语料库数据集样本量失衡严重，感谢博主分享和指导

**Comment by Sanster** [comment]
- 这里有一些语料：https://github.com/Sanster/text_renderer/issues/6#issuecomment-408352902
- 要使字符平衡，最简单的方法是先统计下低频的字符，然后随机抽低频字符生成数据，会有一定帮助，但这样生成的数据没有语义信息
- 近期会在 https://github.com/oh-my-ocr 发布一个新版本的 text_renderer，设计上更模块化，会留有做字符平衡的接口，方便实现各种策略。

**Comment by Ianwtg** [comment]
感谢博主的解答和指导
